### ISSUE TITLE
Questions about code

### ISSUE THREAD

**Issue by vabka** [dend35/TaskQuery#1]
Why method Stop is not async?
Sometimes we need to save state on a stop in some database for example. 
https://github.com/dend35/DeferredTask/blob/343d609a267b85cfd8cb79120385eb3a673582a1/DeferredTask/Services/DeferredTaskService.cs#L16

**Comment by dend35** [comment]
https://github.com/dend35/DeferredTask/blob/c279150a848b8e0b4fc58d758cdbca8ad5d51bcf/DeferredTask/Services/DeferredTaskService.cs#L21
